### PR TITLE
enables admin_role module

### LINKED ISSUE #748: Enable localgov_admin by default
Follow-on from https://github.com/localgovdrupal/localgov_core/pull/234

### PR DESCRIPTION
**Pull request by markconroy**
Closes #748 

## What does this change?
Enables the new `localgov_admin_role` module, so we have a consistent way of working with an admin role.

## How to test
Install the distro, check that there is now an 'Admin' role and that is set to be the role used for the administrator role.

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

### CODE REVIEW

**Review by ekes — CHANGES_REQUESTED** [review]
Waiting on https://github.com/localgovdrupal/localgov_core/pull/238 first. 

The required version will also need bumping in composer.json so that the module does exist before it tries to install it.

**Comment by andybroomfield** [comment]
I'm getting the following error about missing the localgov_admin_role module, which is becuase I have a different branch of localgov_core checked out, but this reminds us that we should now bump up the minimum version of localgov_core in the profile to make sure the sub module it there.

```
Required modules:Required modules not found.<br /><br />The following modules are required but were not found. Move them into the appropriate modules subdirectory, such as <em>/modules</em>. Missing modules:   
                                                                                                                                                                                                                    
  <!-- THEME DEBUG -->                                                                                                                                                                                              
  <!-- THEME HOOK: 'item_list' -->                                                                                                                                                                                  
  <!-- 💡 BEGIN CUSTOM TEMPLATE OUTPUT from 'core/themes/claro/templates/classy/dataset/item-list.html.twig' -->                                                                                                    
  <div class="item-list--comma-list item-list"><ul class="item-list__comma-list"><li><span class="admin-missing">Localgov_admin_role</span></li></ul></div>                                                         
  <!-- END CUSTOM TEMPLATE OUTPUT from 'core/themes/claro/templates/classy/dataset/item-list.html.twig' -->         
```

**Review by andybroomfield — APPROVED** [review]
This installed the admin role and I could create an administrator and log in as such and perform admin actions.

Screenshot 2024-08-09 at 11 32 07 AM

Note: This required me to be on latest 2.x of localgov_core, as the admin role is not yet included in a release.

Thought: Maybe just rename the role label as Administrator, keep localgov_admin as the internal machine name.

**Review by stephen-cox — APPROVED** [review]
:+1: We can get this merged and released now the module as been released as part of LGD Core

**Comment by markconroy** [comment]
@ekes you requested changes in this. Is it okay for you now? Or is there more to do?

**Review by ekes — APPROVED** [review]

**Pull request merged**
