### PR TITLE
Patch Preview Link module for 'Automatically populating multiple preview link entities'

### PR DESCRIPTION
**Pull request by stephen-cox**
Drupal issue: https://www.drupal.org/project/preview_link/issues/3439968
Gitlab MR: https://git.drupalcode.org/project/preview_link/-/merge_requests/28

Part of #600

### CODE REVIEW

**Comment by stephen-cox** [comment]
Marking as draft as I need to add some tests and then we can lock the patch file to a specific commit.

**Comment by stephen-cox** [comment]
This is now ready for review.

This PR simply patches Preview Link. To see it in action you also need the plugins in Guides and Step by Steps which are here:

* https://github.com/localgovdrupal/localgov_guides/pull/163
* https://github.com/localgovdrupal/localgov_step_by_step/pull/98

**Comment by stephen-cox** [comment]
There are also PRs adding populate preview link buttons to Directories (https://github.com/localgovdrupal/localgov_directories/pull/376) and Subsites (https://github.com/localgovdrupal/localgov_subsites/pull/146)

**Comment by stephen-cox** [comment]
@ekes @finnlewis Would be nice to get this reviewed and merge :smile:

**Comment by ekes** [comment]
I'd missed this patch. Testing with step-by-step first.

My note on subsites, about levels/depth, still stands though.

**Review by ekes — APPROVED** [review]
OK so we're already similarly patching this module, so we're hooked there already.
Looked at the plugin and tests and all looks good. Also tested with step-by-step and directories manually.

**Pull request merged**
