### PR TITLE
Set default admin theme to Gin theme with a horizontal toolbar.

### LINKED ISSUE #148: LocalGov Drupal Admin UX
A number of us are keen to make sure the admin user expeirence is as good as possible in LocalGov Drupal.

Lambeth is launching the first section of content next week and we're keen to make sure content designers have the best start. 

To this end, we've created a localgov_claro repository to start investigating how a sub-theme of Claro might help.

We're also looking at elbow_room and other contrib to assist in tidying up the node/add node/edit forms. 

Any thoughts or suggestions ? 

@andybroomfield @Adnan-cds @stephen-cox @cjstevens78 @ekes @paulpopus @willguv

### PR DESCRIPTION
**Pull request by finnlewis**
Does what it says.

Won't have any effect on existing sites, just defaults for new installs. 

See end of https://github.com/localgovdrupal/localgov/issues/148 

CC @willguv @markconroy @msayoung @danchamp @stephen-cox @andybroomfield

### CODE REVIEW

**Comment by andybroomfield** [comment]
Is there a paticular reason / preference for it to be the horizontal?
Wonder what the reasoning was to go vertical by default.
(Personally I find the vertical easier, although you do have to remember the icons or find the expand slider).

**Comment by markconroy** [comment]
I find the vertical very confusing, can't ever remember what icon is for what, and I think that might get more confusing as more features are added, especially if a top level item doesn't have an icon.

Horizontal FTW.

**Comment by danchamp** [comment]
It's funny how personal preferences differ, the vertical icons make my head hurt. Sorry @andybroomfield!

**Review by danchamp — APPROVED** [review]
Happy to see this @finnlewis, thanks.

**Comment by willguv** [comment]
Is it easy to switch, and have users set their own preference?

As we’ve seen on this thread, people will have their preferred layout and we ought to investigate providing that

**Comment by andybroomfield** [comment]
@willguv  It's a preference in the the theme settings and users can override in user profile if it's enabled.

**Comment by willguv** [comment]
Thanks @andybroomfield. Feels like we should enable this and give users the choice

My preference for the default is the one that gives the most guidance to new users

I can’t remember if the horizontal layout has text and icons?

**Comment by andybroomfield** [comment]
@danchamp I think it's remembering which icons are which so it's not great discovery till you find the expand slider.

It's more the long list of items in a menu does scroll in the vertical one.

**Comment by willguv** [comment]
Also sorry for closing - butter fingers on phone

**Pull request merged**
