### PR TITLE
Add localgov guides

### PR DESCRIPTION
**Pull request by ekes**
Add LocalGov Guides to distro.

Review:
  *   localgovdrupal/localgov_guides#1
  *   localgovdrupal/localgov_guides#2
  *   localgovdrupal/localgov_guides#3
  *   localgovdrupal/localgov_guides#5

Includes 378d0fb to for PR localgovdrupal/localgov_services#49 which related and needed for tests. Should be reverted before merge.

### CODE REVIEW

**Comment by ekes** [comment]
> The previous and next links don't display.

There are no templates yet for the nodes types. So the theming has a separate issue.

Although I notice, while working on step-by-step (which implements the navigation with views) it uses a block for the prev/next as well. But what's there is the block for the contents that's generated by code (see additional issue about deleting pages - which has the commented out failing test that's causing the bulk of the phpcs errors) but needs to be placed; and the links that are injected into the template (but no template using it yet).

**Comment by ekes** [comment]
> There are coding standards issues

Should be fixed.

**Comment by finnlewis** [comment]
@ekes just trying to test this locally, but changing the root composer.json 
```
-        "localgovdrupal/localgov": "dev-master"
+        "localgovdrupal/localgov": "dev-feature/localgov_guides"
```
Then re-running the composer and site install.

I get the following
```
Configuration objects provided by <em class="placeholder">localgov_services_page</em> have unmet dependencies: <em class="placeholder">field.field.node.localgov_services_page.field_all_topics (taxonomy.vocabulary.topic), field.field.node.localgov_serv  
  ices_page.field_topic_term (field.storage.node.field_topic_term)</em>  
```
Am I doing it wrong?

**Comment by ekes** [comment]
Cache maybe, the `field.field.node.localgov_services_page.field_all_topics` ( has updated in master to
https://github.com/localgovdrupal/localgov_services/blob/9f774fb41af4156228aadfd463be9f74a5d00675/modules/localgov_services_page/config/install/field.field.node.localgov_services_page.field_all_topics.yml#L7
https://github.com/localgovdrupal/localgov_services/blob/9f774fb41af4156228aadfd463be9f74a5d00675/modules/localgov_services_page/config/install/field.field.node.localgov_services_page.field_all_topics.yml#L22
And `field_topic_term` is renamed.

**Comment by ekes** [comment]
Oh hold up. It depends on a branch of services doesn't it. I'll update that branch with master.

**Comment by ekes** [comment]
> Oh hold up. It depends on a branch of services doesn't it. I'll update that branch with master.

Should be updated.

**Comment by stephen-cox** [comment]
This now installs fine for me

**Pull request merged**
