### PR TITLE
Feature/49 sitemap

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by ekes** [comment]
Where do we want to put enabling it, and any shared configuration?

The entity / type specific stuff should live as optional configuration I think. But are there global settings?

**Comment by finnlewis** [comment]
I guess enabling it in https://github.com/localgovdrupal/localgov/blob/master/localgov.info.yml makes sense for now... then figure out what, if any specific config needs initiating?

**Comment by ekes** [comment]
Is there likely to be a lot more straight SEO stuff. Such that it would want its own submodule?

That said unless it's obvious. Can put in the .info.yml for now; and move if it makes sense.

**Comment by finnlewis** [comment]
How's that @ekes ?
I guess that config for each content type needs to live with that module, but at least it is now there and enabled by default.

**Comment by ekes** [comment]
> I guess that config for each content type needs to live with that module, 

Yes. I'd put the services ones in optional:

https://github.com/localgovdrupal/localgov_services/blob/master/modules/localgov_services_landing/config/optional/simple_sitemap.bundle_settings.default.node.localgov_services_landing.yml

**Comment by ekes** [comment]
For the rest. Having it in the profile level probably makes sense. There's nothing else that it does. And if there is more SEO it can be moved.

**Comment by finnlewis** [comment]
@ekes I've now added simple_sitemap and some default configuration.

Also moved the existing optional configuration to default on https://github.com/localgovdrupal/localgov_services/pull/53

**Comment by finnlewis** [comment]
Hi @ekes 

I've updated the issue with my findings here https://github.com/localgovdrupal/localgov/issues/49

Since the optional configuration does not appear to be working, a good starting point is just to include the configuration for simpel_sitemap in the profile for the services content types. 

We can address the others (guides / step by step) in their own modules.

How does that sound for now?

Cheers,

Finn

**Comment by finnlewis** [comment]
@stephen-cox the reason it is here and not in the services module, is that the services modules might be installed without the profile and without simple_sitemap, and the config/optional does not work for the simple_sitemap bundle config. 

We can move later if we resolve that. For now, at least we have sensible defaults on install.

**Pull request merged**
