### PR TITLE
Enable stable9 theme if localgov_base theme is enabled 

### PR DESCRIPTION
**Pull request by stephen-cox**
Part of localgovdrupal/localgov_base#347

### CODE REVIEW

**Review by markconroy — COMMENTED** [review]
I'd probably remove the `if` statement here and just enable stable9 across the board. I don't see any downsides to it.

**Comment by stephen-cox** [comment]
I'm not sure enabling stuff for everyone that might not be needed is a good thing and I think the condition catches everyone using a `localgov_base` based theme with the distribution. They will need localgov_base enabled and so will get stable9 enabled . Happy to discuss though.

**Review by finnlewis — APPROVED** [review]
This works for me locally, thanks @stephen-cox !
https://github.com/localgovdrupal/localgov_base/pull/347 then also works nicely without errors. 
Phew!

**Comment by stephen-cox** [comment]
Discussed at Merge Monday and the preference is to only enable stable9 when needed and so to keep the condition.

**Pull request merged**
