### PR TITLE
Add localgov_openreferral to composer json, initially to test the loc…

### PR DESCRIPTION
**Pull request by finnlewis**
…algov_directories feature/2.x/261-Open-Referral branch.

### CODE REVIEW

**Comment by finnlewis** [comment]
This should help us to test https://github.com/localgovdrupal/localgov_directories/tree/feature/2.x/261-Open-Referral

**Comment by finnlewis** [comment]
```1) Drupal\Tests\localgov_openreferral\Functional\ResourceTest::testUnpublishedAccess
Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for views.view.localgov_openreferral_services with the following errors: views.view.localgov_openreferral_services:display.default.display_options.query.options.bypass_access missing schema, views.view.localgov_openreferral_services:display.default.display_options.query.options.skip_access missing schema, views.view.localgov_openreferral_services:display.default.display_options.query.options.preserve_facet_query_args missing schema, views.view.localgov_openreferral_services:display.openreferral_json.display_options.style.options.formats missing schema 
```

@ekes I'm just looking at the missing schema error and came across this : https://www.drupal.org/project/search_api/issues/3196990

I don't fully understand, but is it worth trying that patch? Or might we be able to just change the query type in our configuration?

**Comment by ekes** [comment]
Looks like that patch will go in if it gets tests; and Thomas (drunkenmonkey) is usually good about getting these things committed and followed-up.

So I'd go with trying out this patch, and maybe we can contribute some tests - if I can understand it!

**Comment by ekes** [comment]
Initial feedback: still got one schema error left `views.view.localgov_openreferral_services:display.openreferral_json.disp
lay_options.style.options.formats`

Ach. I can probably fix that one - yep.

Then the next one https://github.com/localgovdrupal/localgov_directories/issues/163

**Comment by finnlewis** [comment]
Woops - sorry @ekes - I was just merging back to get rid of some of the failing tests, didn't mean to cross streams!

 I'm leaving it again for now and will check in on Monday.

**Comment by ekes** [comment]
Woot! GREEN.

**Review by andybroomfield — APPROVED** [review]
Ok, to get new open referral experimental modules.

**Comment by ekes** [comment]
GREEN \o/

**Review by ekes — APPROVED** [review]

**Pull request merged**
