### PR TITLE
Include localgov_search 1.0.0

### LINKED ISSUE #259: Site-wide search - default implementation  out of the box
## User story

As a content designer
I want: site wide search out of the box
So that: I can have basic search 

## Assumptions: 

 - basic first pass
 - all content types to be indexed
 - fields to be indexed: rendered page or a specific view mode
 - search result view mode (check with @markconroy )
 - no filters (for now)
 - minimal theme work for now, but test in current localgov_theme theme

## Acceptance tests

 - from a default install:
 - go to /search 
 - see search box
 - search for a thing
 - see a list of relevant things

## Tasks:

- [x] whip up a wireframe 
- [x] set up new module with search api dependency etc. 
- [x] search view config for /search
- [x] search index view mode on all content types
- [x] search result view mode on all content types
- [x] Implement wireframe
- [x] Tests

### PR DESCRIPTION
**Pull request by stephen-cox**
This is a pull request for a general review of the [LocalGov Search](https://github.com/localgovdrupal/localgov_search) module.

For review is the localgov_search module and then a number of related pull requests:

- https://github.com/localgovdrupal/localgov_directories/pull/120
- https://github.com/localgovdrupal/localgov_guides/pull/59
- https://github.com/localgovdrupal/localgov_step_by_step/pull/38
- https://github.com/localgovdrupal/localgov_events/pull/35
- https://github.com/localgovdrupal/localgov_services/pull/120
- https://github.com/localgovdrupal/localgov_theme/pull/195

Not sure the best way to do this, so open to alternatives. It probably makes sense to create issues in the search module for problems / suggestions with the search and comment on the pull requests for things related to them.

This work is currently deployed to the testing site: https://test.localgovdrupal.org/search?s=blue+badge

To install it locally, use the `feature/localgov-259-search-2.x` branch of the [project](https://github.com/localgovdrupal/localgov_project/tree/feature/localgov-259-search-2.x)

### CODE REVIEW

**Comment by finnlewis** [comment]
@stephen-cox - I've approved most of the pull requests you link to above.

But https://github.com/localgovdrupal/localgov_theme/pull/195 is best left to @cjstevens78 and/or @markconroy 

Once that's reviewed and merged, this should be unblocked, no?

**Comment by stephen-cox** [comment]
I think the localgov_search module could still do with a code review. It doesn't have to be in depth, but a second set of eyes on it before it's included in the profile would be good.

**Comment by finnlewis** [comment]
I've read through all the code on and I have nothing constuctive to suggest. 

I like the kernel test that checks that new content types are added to the search index, and that enabling the module adds existing content types. That's nice! 

Happy to jump on a call tomorrow and talk over the code if there's anything specific you'd like to cover, but it looks good to me!

Thanks @stephen-cox !

**Comment by ekes** [comment]
Yep also looked through; and my only concern was module enabling order - which is tested. 
I'm not sure I quite follow the hooks about requiring search term, and hiding results if not there.

**Comment by stephen-cox** [comment]
Updated to include the 1.0.0 version of search. Tests will fail until this is released here: https://github.com/localgovdrupal/localgov_search/pull/2

**Review by danchamp — APPROVED** [review]
Installed and tested locally, works just as expected. Thanks @stephen-cox

**Pull request merged**
