### PR TITLE
Test database updates

### LINKED ISSUE #196: Write CI pipeline for automating the db-dump import / upgrade test
From #181 

- [ ] Write pipeline for automating the db-dump import / upgrade test
- [ ] Captruing database, storing db, working out how to import it, docker, Github CI etc. (Estimate: 8)

## Acceptance tests

 - t.b.c.

### PR DESCRIPTION
**Pull request by stephen-cox**
Closes #196

### CODE REVIEW

**Comment by stephen-cox** [comment]
This PR may not be complete but demonstrates how to test the upgrade between version can work.

All comments welcome

**Comment by ekes** [comment]
It would feel nice if we can run a test that does that install based on the db; and runs the update; but then runs the existing tests for the content. 

But then I guess just cut & paste from the tests would do it actually, so it's fixed at the point of the database itself too, and doesn't change later.

**Comment by stephen-cox** [comment]
Getting a bit stuck on this with the demo content module.

The length of some of the tables created by the Search API database index are too long when the test database table prefix is added added and I'm not sure if there's anything that can be done about it.

Errors look like

```
Testing 
Drupal\Tests\localgov\Functional\LocalGovUpdate
 ✘ Update
   │
   │ Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'test62836433search_api_db_localgov_directories_index_default_localgov_di_1' is too long: CREATE TABLE {search_api_db_localgov_directories_index_default_localgov_di_1} (
   │ `item_id` VARCHAR(150) NOT NULL, 
   │ `value` BIGINT NOT NULL, 
   │ PRIMARY KEY (`item_id`, `value`), 
   │ INDEX `_value` (`value`)
   │ ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8; Array
   │ (
   │ )
   │ 
   │ 
   │ /app/web/core/lib/Drupal/Core/Database/Connection.php:701
   │ /app/web/core/lib/Drupal/Core/Database/Connection.php:665
   │ /app/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php:357
   │ /app/web/core/lib/Drupal/Core/Database/Schema.php:656
   │ /app/web/profiles/contrib/localgov/tests/fixtures/localgov-1.0.0.php.gz:82031
   │ /app/web/core/tests/Drupal/FunctionalTests/Update/UpdatePathTestBase.php:233
   │ /app/web/core/tests/Drupal/FunctionalTests/Update/UpdatePathTestBase.php:212
   │ /app/web/core/tests/Drupal/FunctionalTests/Update/UpdatePathTestBase.php:181
   │ 
   │ Caused by
   │ PDOException: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'test62836433search_api_db_localgov_directories_index_default_localgov_di_1' is too long
   │ 
   │ /app/web/core/lib/Drupal/Core/Database/Statement.php:59
   │ /app/web/core/lib/Drupal/Core/Database/Connection.php:640
   │ /app/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php:357
   │ /app/web/core/lib/Drupal/Core/Database/Schema.php:656
   │ /app/web/profiles/contrib/localgov/tests/fixtures/localgov-1.0.0.php.gz:82031
   │ /app/web/core/tests/Drupal/FunctionalTests/Update/UpdatePathTestBase.php:233
   │ /app/web/core/tests/Drupal/FunctionalTests/Update/UpdatePathTestBase.php:212
   │ /app/web/core/tests/Drupal/FunctionalTests/Update/UpdatePathTestBase.php:181
   │ 

Time: 3.47 seconds, Memory: 12.00 MB


ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by stephen-cox** [comment]
Tests for this are now passing but I've had to drop the content tests for events and directories, because the Drupal database import testing framework can't handle the Search API DB table lengths, and subsites because Github CI fails on these tests even though they pass on my local setup.

Question is, do we feel this is okay for now or do we want to get this all working before merging?

This is the remaining blocker to a LocalGov 2.0.0 release

**Comment by finnlewis** [comment]
Amazing, well done @stephen-cox !

I'd be happy with this, as long as we have separate issues open to try to fix the tests with the content that we have omitted.

**Comment by finnlewis** [comment]
@andybroomfield @Adnan-cds what do you think?

**Comment by finnlewis** [comment]
Just added this issue to remind us to try to fix the Search API content testing: 
https://github.com/localgovdrupal/localgov/issues/244

**Comment by finnlewis** [comment]
@andybroomfield you happy to approve this now that the tests are passing and we've tracked up another issue to try to fix the Search API content testing?

**Comment by andybroomfield** [comment]
I don't know enough about GitHub testing to be able to comment, but since this does not effect sites, it should be fine to go ahead with just agile collective if it's is just infrastructure.

**Review by finnlewis — APPROVED** [review]
I'm happy with this for now, we will pick up the strange testing issue in https://github.com/localgovdrupal/localgov/issues/244

**Pull request merged**
