### PR TITLE
Pin branches to test fixes ahead of merge and release.

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by andybroomfield** [comment]
Local test results (ran overnight with all branches checked out)
````
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Testing 
Drupal\Tests\localgov\Functional\LocalGovProfile
 ✔ Local gov drupal profile

Drupal\Tests\localgov_alert_banner\Functional\AdminView
 ✔ Load admin view

Drupal\Tests\localgov_alert_banner\Functional\AlertBannerBlock
 ✔ Alert banner displays
 ✔ Non live alert banner does not display
 ✔ Alert display title
 ✔ Alert remove hide link

Drupal\Tests\localgov_alert_banner\Functional\AlertConfirmation
 ✔ Alert confirmation
 ✔ Save alert redirect

Drupal\Tests\localgov_alert_banner\Functional\Permissions
 ✔ Alert banner user access

Drupal\Tests\localgov_alert_banner\Functional\ViewsStatusLink
 ✔ Entity link

Drupal\Tests\localgov_alert_banner\FunctionalJavascript\AlertBannerHide
 ✔ Alert banner hide

Drupal\Tests\localgov_alert_banner\Kernel\AlertBannerBlockOrder
 ✔ Alert banner block order

Drupal\Tests\localgov_media\Functional\MediaSetup
 ✔ Media bundles
 ✔ Image croppers in image edit form

Drupal\Tests\localgov_workflows\Kernel\WorkflowsInstall
 ✔ Enable module

Drupal\Tests\localgov_core\Functional\PageHeaderBlock
 ✔ Page header block display
 ✔ Page header display event

Drupal\Tests\localgov_core\Kernel\FieldRenameHelper
 ✔ Rename field

Drupal\Tests\localgov_directories_page\Functional\DirectoryPage
 ✔ Directory page fields

Drupal\Tests\localgov_directories_page\Functional\PathIntegration
 ✔ Directory integration

Drupal\Tests\localgov_directories_venue\Functional\DirectoryVenue
 ✔ Directory venue fields

Drupal\Tests\localgov_directories\Functional\ChannelFacetsWidgetAdmin
 ✔ Directory channel widget

Drupal\Tests\localgov_directories\Functional\ServicesIntegration
 ✔ Services integration

Drupal\Tests\localgov_directories\FunctionalJavascript\EntityReferenceFacetsWidget
 ✔ Directory channel widget
 ✔ Facet required

Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelection
 ✔ Selection handler

Drupal\Tests\localgov_directories\Kernel\EntityReferenceDirectoryEntryTypes
 ✔ Selection handler

Drupal\Tests\localgov_directories\Kernel\FacetIndexFieldSetup
 ✔ Facet index field creation

Drupal\Tests\localgov_directories\Kernel\IgnoreTypeConfig
 ✔ Excluded modules

Drupal\Tests\localgov_directories\Unit\FacetPreprocess
 ✔ Facet type sorting

Drupal\Tests\localgov_events\Functional\EventPage
 ✔ Event fields

Drupal\Tests\localgov_guides\Functional\ContentsBlock
 ✔ Contents block visibility
 ✔ Content list block

Drupal\Tests\localgov_guides\Functional\GuidePages
 ✔ Config form

Drupal\Tests\localgov_guides\Functional\PageHeaderBlock
 ✔ Guide page header block

Drupal\Tests\localgov_guides\Functional\PagesIntegration
 ✔ Topic integration
 ✔ Services integration
 ✔ Page path

Drupal\Tests\localgov_guides\Functional\PrevNextBlock
 ✔ Prev next block

Drupal\Tests\localgov_menu_link_group\Kernel\CrossMenuAssignment
 ✔ Form submission

Drupal\Tests\localgov_menu_link_group\Kernel\GroupConfigImport
 ✔ Menu link alteration
 ✔ Duplicate group

Drupal\Tests\localgov_homepage_paragraphs\Functional\HomepageAdd
 ✔ Create homepage

Drupal\Tests\localgov_paragraphs\Functional\ParagraphsAdministration
 ✔ Paragraphs types
 ✔ Paragraphs creation

Drupal\Tests\localgov_services_landing\Functional\ServicesLandingPage
 ✔ Service landing page

Drupal\Tests\localgov_services_navigation\FunctionalJavascript\EntityReferenceServicesAutocomplete
 ✔ Services entity reference autocomplete widget
 ✔ Entity reference autocomplete widget
 ✔ Entity reference sublanding label widget

Drupal\Tests\localgov_services_navigation\FunctionalJavascript\LandingPageChildren
 ✔ Service landing page link
 ✔ Service landing page reference

Drupal\Tests\localgov_services_navigation\Kernel\ChildReferences
 ✔ Referenced children
 ✔ Add child target

Drupal\Tests\localgov_services_navigation\Kernel\ParentFieldPathauto
 ✔ Service parent addition

Drupal\Tests\localgov_services_page\Functional\ServicesPage
 ✔ Services page

Drupal\Tests\localgov_services_status\Functional\ServiceStatus
 ✔ Service status pages
 ✔ Service status listings
 ✔ Service status path

Drupal\Tests\localgov_services_status\Kernel\Path
 ✔ Process inbound
 ✔ Process outbound

Drupal\Tests\localgov_services_sublanding\Functional\ServiceSublanding
 ✔ Service sublanding pages

Drupal\Tests\localgov_services_sublanding\Functional\TopicListBuilder
 ✔ Topic list builder paragraph display

Drupal\tests\localgov_services_sublanding\Functional\UnpublishedLinkNodeReference
 ✔ Only list published child pages
 ✔ Highlight unpublished child pages

Drupal\Tests\localgov_services\Functional\PagesIntegration
 ✔ Config form
 ✔ Post link
 ✔ Service paths

Drupal\Tests\localgov_services\Functional\ServicesBlock
 ✔ Service core blocks display

Drupal\Tests\localgov_step_by_step\Functional\PagesIntegration
 ✔ Topic integration
 ✔ Services integration
 ✔ Page path

Drupal\Tests\localgov_step_by_step\Functional\StepByStepBlocks
 ✔ Part of step block

Drupal\Tests\localgov_step_by_step\Functional\StepByStepPages
 ✔ Config form

Drupal\Tests\localgov_alert_banner\FunctionalJavascript\StepByStepSummaries
 ✔ Step summary visibility

Drupal\Tests\localgov_subsites_paragraphs\Functional\SubsitesParagraphsAdministration
 ✔ Subsite paragraphs types

Drupal\Tests\localgov_subsites\Functional\SubsiteBlocks
 ✔ Subsite banner block
 ✔ Subsite navigation block

Drupal\Tests\localgov_subsites\Functional\SubsitePages
 ✔ Subsite fields
 ✔ Subsite paths

Time: 3.93 hours, Memory: 12.00 MB

OK (79 tests, 1218 assertions)

Remaining deprecation notices (40)

  35x: Duplicate key "height" detected whilst parsing YAML. Silent handling of duplicate mapping keys in YAML is deprecated since Symfony 3.2 and will throw \Symfony\Component\Yaml\Exception\ParseException in 4.0 on line 134.
    1x in PagesIntegrationTest::testTopicIntegration from Drupal\Tests\localgov_step_by_step\Functional
    1x in UnpublishedLinkNodeReferenceTest::testOnlyListPublishedChildPages from Drupal\tests\localgov_services_sublanding\Functional
    1x in UnpublishedLinkNodeReferenceTest::testHighlightUnpublishedChildPages from Drupal\tests\localgov_services_sublanding\Functional
    1x in PagesIntegrationTest::testConfigForm from Drupal\Tests\localgov_services\Functional
    1x in PagesIntegrationTest::testPostLink from Drupal\Tests\localgov_services\Functional
    1x in PagesIntegrationTest::testServicePaths from Drupal\Tests\localgov_services\Functional
    1x in ServicesBlockTest::testServiceCoreBlocksDisplay from Drupal\Tests\localgov_services\Functional
    1x in PagesIntegrationTest::testServicesIntegration from Drupal\Tests\localgov_step_by_step\Functional
    1x in ServiceSublandingTest::testServiceSublandingPages from Drupal\Tests\localgov_services_sublanding\Functional
    1x in PagesIntegrationTest::testPagePath from Drupal\Tests\localgov_step_by_step\Functional
    1x in StepByStepSummariesTest::testStepSummaryVisibility from Drupal\Tests\localgov_alert_banner\FunctionalJavascript
    1x in SubsitesParagraphsAdministrationTest::testSubsiteParagraphsTypes from Drupal\Tests\localgov_subsites_paragraphs\Functional
    1x in SubsiteBlocksTest::testSubsiteBannerBlock from Drupal\Tests\localgov_subsites\Functional
    1x in SubsiteBlocksTest::testSubsiteNavigationBlock from Drupal\Tests\localgov_subsites\Functional
    1x in SubsitePagesTest::testSubsiteFields from Drupal\Tests\localgov_subsites\Functional
    1x in TopicListBuilderTest::testTopicListBuilderParagraphDisplay from Drupal\Tests\localgov_services_sublanding\Functional
    1x in ServiceStatusTest::testServiceStatusPath from Drupal\Tests\localgov_services_status\Functional
    1x in LocalGovProfileTest::testLocalGovDrupalProfile from Drupal\Tests\localgov\Functional
    1x in ParagraphsAdministrationTest::testParagraphsCreation from Drupal\Tests\localgov_paragraphs\Functional
    1x in AlertBannerHideTest::testAlertBannerHide from Drupal\Tests\localgov_alert_banner\FunctionalJavascript
    1x in ServicesIntegrationTest::testServicesIntegration from Drupal\Tests\localgov_directories\Functional
    1x in PagesIntegrationTest::testTopicIntegration from Drupal\Tests\localgov_guides\Functional
    1x in PagesIntegrationTest::testServicesIntegration from Drupal\Tests\localgov_guides\Functional
    1x in PagesIntegrationTest::testPagePath from Drupal\Tests\localgov_guides\Functional
    1x in ParagraphsAdministrationTest::testParagraphsTypes from Drupal\Tests\localgov_paragraphs\Functional
    1x in ServicesLandingPageTest::testServiceLandingPage from Drupal\Tests\localgov_services_landing\Functional
    1x in ServiceStatusTest::testServiceStatusListings from Drupal\Tests\localgov_services_status\Functional
    1x in EntityReferenceServicesAutocompleteTest::testServicesEntityReferenceAutocompleteWidget from Drupal\Tests\localgov_services_navigation\FunctionalJavascript
    1x in EntityReferenceServicesAutocompleteTest::testEntityReferenceAutocompleteWidget from Drupal\Tests\localgov_services_navigation\FunctionalJavascript
    1x in EntityReferenceServicesAutocompleteTest::testEntityReferenceSublandingLabelWidget from Drupal\Tests\localgov_services_navigation\FunctionalJavascript
    1x in LandingPageChildrenTest::testServiceLandingPageLink from Drupal\Tests\localgov_services_navigation\FunctionalJavascript
    1x in LandingPageChildrenTest::testServiceLandingPageReference from Drupal\Tests\localgov_services_navigation\FunctionalJavascript
    1x in ServicesPageTest::testServicesPage from Drupal\Tests\localgov_services_page\Functional
    1x in ServiceStatusTest::testServiceStatusPages from Drupal\Tests\localgov_services_status\Functional
    1x in SubsitePagesTest::testSubsitePaths from Drupal\Tests\localgov_subsites\Functional

  2x: The \Drupal\Core\Path\AliasManager class is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Instead, use \Drupal\path_alias\AliasManager. See https://drupal.org/node/3092086
    2x in TopicListBuilderTest::testTopicListBuilderParagraphDisplay from Drupal\Tests\localgov_services_sublanding\Functional

  1x: Drupal\Tests\BrowserTestBase::$defaultTheme is required in drupal:9.0.0 when using an install profile that does not set a default theme. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.
    1x in PermissionsTest::testAlertBannerUserAccess from Drupal\Tests\localgov_alert_banner\Functional

  1x: Drupal\Component\Plugin\ConfigurablePluginInterface is deprecated in Drupal 8.7.0 and will be removed before Drupal 9.0.0. You should implement ConfigurableInterface and/or DependentPluginInterface directly as needed. If you implement ConfigurableInterface you may choose to implement ConfigurablePluginInterface in Drupal 8 as well for maximum compatibility, however this must be removed prior to Drupal 9. See https://www.drupal.org/node/2946161
    1x in EventPageTest::testEventFields from Drupal\Tests\localgov_events\Functional

  1x: Entity type "date_recur_interpreter" is using config schema as a fallback for a missing `config_export` definition is deprecated in Drupal 8.7.0 and will be removed before Drupal 9.0.0. See https://www.drupal.org/node/2949023.
    1x in EventPageTest::testEventFields from Drupal\Tests\localgov_events\Functional
````

**Comment by finnlewis** [comment]
Thanks @andybroomfield 

I am also testing locally on all branches. 

Trying to get all the composer branches in line for automated testing on Github is a pain, but I am also trying again with a couple of temporary branches like https://github.com/localgovdrupal/localgov_services/tree/fix/75a-rename-fields to see if we can get the tests passing here too.

**Comment by finnlewis** [comment]
@andybroomfield 

After checking out all the branches listed in the composer.json on this branch 
https://github.com/localgovdrupal/localgov/pull/189/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

phpunit tests all pass locally for me too.

Although, I get fewer deprecation notices than you. 

```
$ lando phpunit
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Testing 
Drupal\Tests\localgov\Functional\LocalGovProfile
 ✔ Local gov drupal profile

Drupal\Tests\localgov_alert_banner\Functional\AdminView
 ✔ Load admin view

Drupal\Tests\localgov_alert_banner\Functional\AlertBannerBlock
 ✔ Alert banner displays
 ✔ Non live alert banner does not display
 ✔ Alert display title
 ✔ Alert remove hide link

Drupal\Tests\localgov_alert_banner\Functional\AlertConfirmation
 ✔ Alert confirmation
 ✔ Save alert redirect

Drupal\Tests\localgov_alert_banner\Functional\Permissions
 ✔ Alert banner user access

Drupal\Tests\localgov_alert_banner\Functional\ViewsStatusLink
 ✔ Entity link

Drupal\Tests\localgov_alert_banner\FunctionalJavascript\AlertBannerHide
 ✔ Alert banner hide

Drupal\Tests\localgov_alert_banner\Kernel\AlertBannerBlockOrder
 ✔ Alert banner block order

Drupal\Tests\localgov_media\Functional\MediaSetup
 ✔ Media bundles
 ✔ Image croppers in image edit form

Drupal\Tests\localgov_workflows\Kernel\WorkflowsInstall
 ✔ Enable module

Drupal\Tests\localgov_core\Functional\PageHeaderBlock
 ✔ Page header block display
 ✔ Page header display event

Drupal\Tests\localgov_core\Kernel\FieldRenameHelper
 ✔ Rename field

Drupal\Tests\localgov_directories_page\Functional\DirectoryPage
 ✔ Directory page fields

Drupal\Tests\localgov_directories_page\Functional\PathIntegration
 ✔ Directory integration

Drupal\Tests\localgov_directories_venue\Functional\DirectoryVenue
 ✔ Directory venue fields

Drupal\Tests\localgov_directories\Functional\ChannelFacetsWidgetAdmin
 ✔ Directory channel widget

Drupal\Tests\localgov_directories\Functional\ServicesIntegration
 ✔ Services integration

Drupal\Tests\localgov_directories\FunctionalJavascript\EntityReferenceFacetsWidget
 ✔ Directory channel widget
 ✔ Facet required

Drupal\Tests\localgov_directories\Kernel\EntityReferenceChannelsSelection
 ✔ Selection handler

Drupal\Tests\localgov_directories\Kernel\EntityReferenceDirectoryEntryTypes
 ✔ Selection handler

Drupal\Tests\localgov_directories\Kernel\FacetIndexFieldSetup
 ✔ Facet index field creation

Drupal\Tests\localgov_directories\Kernel\IgnoreTypeConfig
 ✔ Excluded modules

Drupal\Tests\localgov_directories\Unit\FacetPreprocess
 ✔ Facet type sorting

Drupal\Tests\localgov_events\Functional\EventPage
 ✔ Event fields

Drupal\Tests\localgov_guides\Functional\ContentsBlock
 ✔ Contents block visibility
 ✔ Content list block

Drupal\Tests\localgov_guides\Functional\GuidePages
 ✔ Config form

Drupal\Tests\localgov_guides\Functional\PageHeaderBlock
 ✔ Guide page header block

Drupal\Tests\localgov_guides\Functional\PagesIntegration
 ✔ Topic integration
 ✔ Services integration
 ✔ Page path

Drupal\Tests\localgov_guides\Functional\PrevNextBlock
 ✔ Prev next block

Drupal\Tests\localgov_menu_link_group\Kernel\CrossMenuAssignment
 ✔ Form submission

Drupal\Tests\localgov_menu_link_group\Kernel\GroupConfigImport
 ✔ Menu link alteration
 ✔ Duplicate group

Drupal\Tests\localgov_homepage_paragraphs\Functional\HomepageAdd
 ✔ Create homepage

Drupal\Tests\localgov_paragraphs\Functional\ParagraphsAdministration
 ✔ Paragraphs types
 ✔ Paragraphs creation

Drupal\Tests\localgov_services_landing\Functional\ServicesLandingPage
 ✔ Service landing page

Drupal\Tests\localgov_services_navigation\FunctionalJavascript\EntityReferenceServicesAutocomplete
 ✔ Services entity reference autocomplete widget
 ✔ Entity reference autocomplete widget
 ✔ Entity reference sublanding label widget

Drupal\Tests\localgov_services_navigation\FunctionalJavascript\LandingPageChildren
 ✔ Service landing page link
 ✔ Service landing page reference

Drupal\Tests\localgov_services_navigation\Kernel\ChildReferences
 ✔ Referenced children
 ✔ Add child target

Drupal\Tests\localgov_services_navigation\Kernel\ParentFieldPathauto
 ✔ Service parent addition

Drupal\Tests\localgov_services_page\Functional\ServicesPage
 ✔ Services page

Drupal\Tests\localgov_services_status\Functional\ServiceStatus
 ✔ Service status pages
 ✔ Service status listings
 ✔ Service status path

Drupal\Tests\localgov_services_status\Kernel\Path
 ✔ Process inbound
 ✔ Process outbound

Drupal\Tests\localgov_services_sublanding\Functional\ServiceSublanding
 ✔ Service sublanding pages

Drupal\Tests\localgov_services_sublanding\Functional\TopicListBuilder
 ✔ Topic list builder paragraph display

Drupal\tests\localgov_services_sublanding\Functional\UnpublishedLinkNodeReference
 ✔ Only list published child pages
 ✔ Highlight unpublished child pages

Drupal\Tests\localgov_services\Functional\PagesIntegration
 ✔ Config form
 ✔ Post link
 ✔ Service paths

Drupal\Tests\localgov_services\Functional\ServicesBlock
 ✔ Service core blocks display

Drupal\Tests\localgov_step_by_step\Functional\PagesIntegration
 ✔ Topic integration
 ✔ Services integration
 ✔ Page path

Drupal\Tests\localgov_step_by_step\Functional\StepByStepBlocks
 ✔ Part of step block

Drupal\Tests\localgov_step_by_step\Functional\StepByStepPages
 ✔ Config form

Drupal\Tests\localgov_alert_banner\FunctionalJavascript\StepByStepSummaries
 ✔ Step summary visibility

Drupal\Tests\localgov_subsites_paragraphs\Functional\SubsitesParagraphsAdministration
 ✔ Subsite paragraphs types

Drupal\Tests\localgov_subsites\Functional\SubsiteBlocks
 ✔ Subsite banner block
 ✔ Subsite navigation block

Drupal\Tests\localgov_subsites\Functional\SubsitePages
 ✔ Subsite fields
 ✔ Subsite paths

Time: 41.83 minutes, Memory: 12.00 MB

OK (79 tests, 1218 assertions)

Remaining deprecation notices (5)

  2x: The \Drupal\Core\Path\AliasManager class is deprecated in drupal:8.8.0 and is removed from drupal:9.0.0. Instead, use \Drupal\path_alias\AliasManager. See https://drupal.org/node/3092086
    2x in TopicListBuilderTest::testTopicListBuilderParagraphDisplay from Drupal\Tests\localgov_services_sublanding\Functional

  1x: Drupal\Tests\BrowserTestBase::$defaultTheme is required in drupal:9.0.0 when using an install profile that does not set a default theme. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.
    1x in PermissionsTest::testAlertBannerUserAccess from Drupal\Tests\localgov_alert_banner\Functional

  1x: Drupal\Component\Plugin\ConfigurablePluginInterface is deprecated in Drupal 8.7.0 and will be removed before Drupal 9.0.0. You should implement ConfigurableInterface and/or DependentPluginInterface directly as needed. If you implement ConfigurableInterface you may choose to implement ConfigurablePluginInterface in Drupal 8 as well for maximum compatibility, however this must be removed prior to Drupal 9. See https://www.drupal.org/node/2946161
    1x in EventPageTest::testEventFields from Drupal\Tests\localgov_events\Functional

  1x: Entity type "date_recur_interpreter" is using config schema as a fallback for a missing `config_export` definition is deprecated in Drupal 8.7.0 and will be removed before Drupal 9.0.0. See https://www.drupal.org/node/2949023.
    1x in EventPageTest::testEventFields from Drupal\Tests\localgov_events\Functional

**Comment by finnlewis** [comment]
@andybroomfield tests do now pass, as expected.
I'll close this PR

**Pull request closed without merging**
