### PR TITLE
Update simple sitemap to ^4.1

### LINKED ISSUE #558: Update Simple XML Sitemap to version 4 on 2.x branch
Maybe we should consider updating the Simple XML Sitemap to the version 4x branch as the version 3x branch is no longer supported.

### LINKED ISSUE #561: Update simple_sitemap in 2.x branch
Notice that 3.x has been upgraded to Simple site map 4.
We could do with the same in 2.x as 4.1.6 is listed as the only release.

> [4.1.6](https://www.drupal.org/project/simple_sitemap/releases/4.1.6) Stable release covered by the Drupal Security Team released 9 June 2023
> Works with Drupal: ^9.3 || ^10

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #558 

Should be Drupal 9.3+ compatible.

### CODE REVIEW

**Comment by andybroomfield** [comment]
Test fails look like schema errors, did you fix those in the 3.x branch @stephen-cox ?

**Comment by stephen-cox** [comment]
> Test fails look like schema errors, did you fix those in the 3.x branch @stephen-cox ?

Nope. It looks like this is a new config element that needs a schema defining https://git.drupalcode.org/project/simple_sitemap/-/blob/4.x/config/install/simple_sitemap.type.default_hreflang.yml

**Comment by finnlewis** [comment]
See https://www.drupal.org/project/simple_sitemap/issues/3355601

**Comment by finnlewis** [comment]
@andybroomfield @stephen-cox 
tested and fixed the schema error.
Keen to get this merged and tagged. 

Should this be a patch or minor point release?

**Review by finnlewis — APPROVED** [review]

**Review by stephen-cox — COMMENTED** [review]
This causes problems with modules using the old simple_sitemap.generator service. The only one left is Events, so we'll need to merge and release this https://github.com/localgovdrupal/localgov_events/pull/112 before we can merge and release this PR.

**Pull request merged**
