### PR TITLE
Patch Drupal core to avoid tests breaking in PHP 7.4.

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by finnlewis** [comment]
@stephen-cox this PR should help with the tests in PHP 7.4, but it is still testing against PHP 8.

If we can try this with the PHP 7.4 docker image, I am hoping this will get the tests running better again.

CC @Adnan-cds  @andybroomfield  @ekes

**Comment by finnlewis** [comment]
@Adnan-cds @andybroomfield  @ekes @stephen-cox 
This is one of those cases where the tests are not applying the composer.json patch as it is not using it;s own self branch to install via composer. 

Patch is applying and tests are passing locally.

Could one of you just give this a quick look and approve the merge?

I think this will unblock the other testings.

**Comment by Adnan-cds** [comment]
> This is one of those cases where the tests are not applying the composer.json patch as it is not using it;s own self branch to install  via composer.

Would you mind trying the [template test runner ](https://github.com/localgovdrupal/.github/blob/master/workflow-templates/localgov-drupal-ci.yml) for [this repo](https://github.com/localgovdrupal/localgov/blob/master/.github/workflows/test.yml).

**Comment by Adnan-cds** [comment]
The [d.o patch](https://www.drupal.org/files/issues/2021-01-05/fix-php74-tests-3191012-2.patch) looks harmless to me.  Thanks :)

**Review by Adnan-cds — APPROVED** [review]
Looks good to me.  Thanks :)

**Comment by finnlewis** [comment]
Yay! Good call @Adnan-cds ! :+1:

**Pull request merged**
