### PR TITLE
3.0.0 release

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by andybroomfield** [comment]
I've renamed this as the full release PR, as once a couple of other PRs are merged this should be good to go.

**Comment by andybroomfield** [comment]
We are aggreed we can do the full release even though PHP 8.2 test is failing, as per Technical governance meeting with @andybroomfield @finnlewis @ekes present.

**Comment by andybroomfield** [comment]
Note: The patch for entity browser is here https://www.drupal.org/project/entity_browser/issues/3350169

**Comment by finnlewis** [comment]
> Note: The patch for entity browser is here https://www.drupal.org/project/entity_browser/issues/3350169

Haha ! I'm literally just testing that now!

**Comment by finnlewis** [comment]
I'd love to have that last niggly test passing

**Comment by finnlewis** [comment]
Woop woop!

**Comment by finnlewis** [comment]
@andybroomfield - can I can your approval?

**Review by andybroomfield — APPROVED** [review]
Good for release!

**Pull request merged**
