### PR TITLE
Add Campaigns to profile composer file

### PR DESCRIPTION
**Pull request by stephen-cox**
This is more of a meta pull request to review localgov_campaigns work so far: https://github.com/localgovdrupal/localgov_campaigns

These changes are reliant on this pull request: https://github.com/localgovdrupal/localgov_core/pull/21

The main issue is #82, but this has been broken into a number of sub issues. 
Work completed can be seen here: https://github.com/localgovdrupal/localgov_campaigns/issues?q=is%3Aissue+is%3Aclosed
There's still quite a bit to do:https://github.com/localgovdrupal/localgov_campaigns/issues

The main outstanding issue it to review all the page builder paragraphs. The config for these has been moved into it's own module, but that's it.

### CODE REVIEW

**Comment by finnlewis** [comment]
As mentioned, this depends on https://github.com/localgovdrupal/localgov_core/pull/21

So to test, one needs to checkout localgov_core to https://github.com/localgovdrupal/localgov_core/tree/feature/20-entity-reference-labels-widget

**Comment by ekes** [comment]
Think most things can go into issues, I'm just updating that.

I don't quite get what the PageBuilderWidget id 'page_builder_entity_reference_paragraphs' is about though?

**Comment by stephen-cox** [comment]
> I don't quite get what the PageBuilderWidget id 'page_builder_entity_reference_paragraphs' is about though?

I just ported that across. It doesn't seem to do a great deal. Perhaps we just create a separate issue to review how page builder paragraphs are added and edited. Editing nested paragraphs has always seemed a pain to me.

**Comment by ekes** [comment]
So I think localgovdrupal/localgov_campaigns#7  localgovdrupal/localgov_campaigns#11  localgovdrupal/localgov_campaigns#14  localgovdrupal/localgov_campaigns#15 cover all the things to review afterwards.

**Comment by stephen-cox** [comment]
Thanks both. I have the paragraphs basically working here, but there's a bit more today before it will be fully ready for review https://github.com/localgovdrupal/localgov_campaigns/pull/17

**Pull request merged**
