### PR TITLE
enables redirect and redirect_404 by default

### LINKED ISSUE #624: Enable redirect by default
Seems odd it's [missing from this list](https://github.com/localgovdrupal/localgov/blob/3bf25430295beca5b465f775051d9339a84c14e1/localgov.info.yml#L33) ~~though is included in composer.json~~ __is not actully included but comes from localgov_core__  so is there and quite a common feature.
Add `redirect:redirect` to the contrib section of install for it to be enabled by default.

### PR DESCRIPTION
**Pull request by markconroy**
Closes #624 

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

### CODE REVIEW

**Comment by andybroomfield** [comment]
I'd also make sure `drupal/redirect` is added to the profiles composer.json, it's [currently in localgov_cores](https://github.com/localgovdrupal/localgov_core/blob/04bb3a54d3b7e9ff05db3b1fb0863538f155db99/composer.json#L15).

**Comment by markconroy** [comment]
Thanks @andybroomfield. That's added now.

**Review by andybroomfield — APPROVED** [review]
Thanks @markconroy we also need a corresponding one in localgov_core removing the redirect dependnacy from composer.json

**Comment by markconroy** [comment]
@andybroomfield https://github.com/localgovdrupal/localgov_core/pull/223

**Comment by keelanfh** [comment]
Patch should be added here: https://github.com/localgovdrupal/localgov_core/pull/223#issuecomment-2133786343

**Comment by markconroy** [comment]
Thanks @keelanfh - patch moved to the correct place now.

**Pull request merged**
