### PR TITLE
2.0.1 release

### PR DESCRIPTION
**Pull request by stephen-cox**
Includes LocalGov Alert Banner version 1.1.0.

Changelog:

#250 @stephen-cox Patch Drupal core to fix tests running with Paratest
#271 @finnlewis Remove patch for Nested Paragraphs create multiple drag handles 
#272 @stephen-cox Require LocalGov Alert Banner 1.1.0

### CODE REVIEW

**Review by finnlewis — APPROVED** [review]
Not tested locally, but tests pass and it these commits have been approved already. It's a 👍 from me!

**Review by andybroomfield — APPROVED** [review]
Ok to add this, are we agreed this is 2.0.1 and not 2.1?

**Comment by stephen-cox** [comment]
We probably need some guidelines on when a minor release of the profile is required. There will be a release including sitewide search soon. I suggest this should be a minor release rather than a patch release, but let's discuss on that PR once it's created. Doing a 2.0.1 release for now.

**Comment by andybroomfield** [comment]
@stephen-cox backport to 1.x also required?

**Pull request merged**
