### PR TITLE
Release 1.0.0-alpha2

### PR DESCRIPTION
**Pull request by finnlewis**
As suggested by @Adnan-cds - tag a new release to get things working with composer 2.

### CODE REVIEW

**Comment by finnlewis** [comment]
Checks are failing as we also need https://github.com/localgovdrupal/localgov_project/pull/28/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R14

**Comment by finnlewis** [comment]
Just creating this PR to be able to sanity check the commits that are going into the next release tag.
Looks good to me!

**Comment by ekes** [comment]
Probably want to merge and tag a new release of guides and bump that as well for the moving pages fix.

**Review by Adnan-cds — APPROVED** [review]
Looks good.  Thanks for working on this :)

**Pull request merged**
